// src/module-system/a-basefront/front/src/pages/category/categorySelect.vue
<template>
  <eb-page>
    <eb-navbar large largeTransparent :title="$text('Select Category')" eb-back-link="Back">
      <f7-nav-right>
        <eb-link iconMaterial="done" :onPerform="onPerformDone"></eb-link>
      </f7-nav-right>
    </eb-navbar>
    <eb-treeview ref="tree" :root="root" :onLoadChildren="onLoadChildren"> </eb-treeview>
  </eb-page>
</template>
<script>
import Vue from 'vue';
const ebPageContext = Vue.prototype.$meta.module.get('a-components').options.mixins.ebPageContext;
export default {
  mixins: [ebPageContext],
  data() {
    const query = this.$f7route.query;
    const atomClass = {
      module: query.module,
      atomClassName: query.atomClassName,
    };
    const language = query.language;
    return {
      atomClass,
      language,
    };
  },
  computed: {
    categoryIdStart() {
      return this.contextParams.categoryIdStart;
    },
    multiple() {
      return this.contextParams.multiple;
    },
    catalogOnly() {
      return this.contextParams.catalogOnly;
    },
    leafOnly() {
      return this.contextParams.leafOnly;
    },
    categoryIdDisable() {
      return this.contextParams.categoryIdDisable;
    },
    setLocale() {
      return this.contextParams.setLocale;
    },
    root() {
      return {
        attrs: {
          itemToggle: false,
          selectable: false,
          multiple: this.multiple,
          checkbox: true,
          checkOnLabel: true,
        },
      };
    },
  },
  methods: {
    async onLoadChildren(node) {
      // root
      if (node.root && this.categoryIdStart === undefined) {
        const checkbox = !this.leafOnly;
        return [
          {
            id: 0,
            attrs: {
              label: this.$text('Root'),
              toggle: true,
              loadChildren: true,
              checkbox,
              checkOnLabel: checkbox,
              selectable: checkbox,
              itemToggle: !checkbox,
            },
            data: {
              id: 0,
              categoryCatalog: 1,
            },
          },
        ];
      }
      // children
      const categoryId = node.root ? this.categoryIdStart : node.id;
      const data = await this.$api.post('/a/base/category/children', {
        atomClass: this.atomClass,
        language: this.language,
        categoryId,
        setLocale: this.setLocale,
      });
      let list = data.list.map(item => {
        const checkbox = !this.leafOnly || item.categoryCatalog === 0;
        const node = {
          id: item.id,
          attrs: {
            label: item.categoryNameLocale || item.categoryName || `[${this.$text('New Category')}]`,
            toggle: item.categoryCatalog === 1,
            loadChildren: item.categoryCatalog === 1,
            checkbox,
            checkOnLabel: checkbox,
            selectable: checkbox,
            itemToggle: !checkbox,
          },
          data: item,
        };
        return node;
      });
      list = list.filter(item => {
        return (!this.catalogOnly || item.data.categoryCatalog === 1) && (!this.categoryIdDisable || this.categoryIdDisable !== item.id);
      });
      return list;
    },
    onPerformDone() {
      const checked = this.$refs.tree.checked();
      let res;
      if (!checked || checked.length === 0) {
        res = null;
      } else {
        res = checked;
      }
      this.contextCallback(200, res);
      this.$f7router.back();
    },
  },
};
</script>

// src/module-system/a-basefront/front/src/components/category/categorySelect.jsx
export default {
  props: {
    atomClass: {},
    language: {},
    categoryIdStart: {},
    multiple: {},
    catalogOnly: {},
    leafOnly: {},
    categoryIdDisable: {},
    // setLocale: {},
  },
  data() {
    return {};
  },
  computed: {
    root() {
      return {
        attrs: {
          itemToggle: false,
          selectable: false,
          multiple: this.multiple,
          checkbox: true,
          checkOnLabel: true,
        },
      };
    },
  },
  methods: {
    getInstance() {
      return this.$refs.tree;
    },
    _findChildren(children, categoryId) {
      for (const item of children) {
        if (item.id === categoryId) return item.children;
        if (item.children) {
          const res = this._findChildren(item.children, categoryId);
          if (res) return res;
        }
      }
      return null;
    },
    _createNodeRoot(children) {
      const checkbox = !this.leafOnly;
      return [
        {
          id: 0,
          attrs: {
            label: this.$text('Root'),
            toggle: true,
            loadChildren: true,
            checkbox,
            checkOnLabel: checkbox,
            selectable: checkbox,
            itemToggle: !checkbox,
          },
          data: {
            id: 0,
            categoryCatalog: 1,
            children,
          },
        },
      ];
    },
    _createNodeChildren(children) {
      if (!children) return [];
      let nodes = children.map(item => {
        const checkbox = !this.leafOnly || item.categoryCatalog === 0;
        const folder = !checkbox && item.categoryCatalog === 1;
        const node = {
          id: item.id,
          attrs: {
            label: item.categoryNameLocale || item.categoryName || `[${this.$text('New Category')}]`,
            toggle: item.categoryCatalog === 1,
            loadChildren: item.categoryCatalog === 1,
            checkbox,
            checkOnLabel: checkbox,
            selectable: checkbox,
            itemToggle: !checkbox,
            folder,
          },
          data: item,
        };
        return node;
      });
      nodes = nodes.filter(item => {
        return (!this.catalogOnly || item.data.categoryCatalog === 1) && (!this.categoryIdDisable || this.categoryIdDisable !== item.id);
      });
      return nodes;
    },
    async onLoadChildren(node) {
      if (node.root) {
        const treeChildren = await this.$store.dispatch('a/base/getCategoryTree', { atomClass: this.atomClass, language: this.language });
        // append root node
        if (this.categoryIdStart === undefined) {
          return this._createNodeRoot(treeChildren);
        }
        // children
        let children;
        if (this.categoryIdStart === 0) {
          children = treeChildren;
        } else {
          children = this._findChildren(treeChildren, this.categoryIdStart);
        }
        return this._createNodeChildren(children);
      }
      // children
      return this._createNodeChildren(node.data.children);
    },
  },
  render() {
    return <eb-treeview ref="tree" root={this.root} propsOnLoadChildren={this.onLoadChildren}></eb-treeview>;
  },
};
