// src/module-system/a-baselayout/front/src/components/atom/listLayoutBlockTitle.jsx
export default {
  meta: {
    global: false,
  },
  props: {
    layoutManager: {
      type: Object,
    },
    blockConfig: {
      type: Object,
    },
  },
  data() {
    return {
    };
  },
  created() {
  },
  methods: {
  },
  render() {
    return (
      <eb-navbar title={this.layoutManager.getPageTitle()} eb-back-link="Back"></eb-navbar>
    );
  },
};

// src/module-system/a-baselayout/front/src/components/atom/listLayoutBlockTitle.vue
<template>
  <div>
    {{this.layoutConfig}}
  </div>
</template>
<script>
export default {
  meta: {
    global: false,
  },
  props: {
    layoutManager: {
      type: Object,
    },
    layoutConfig: {
      type: Object,
    },
  },
  data() {
    return {
    };
  },
  created() {
  },
  methods: {
  },
};

</script>
