// src/module-system/a-baselayout/front/src/components/atom/listLayoutFilter.jsx
export default {
  meta: {
    global: false,
  },
  props: {
    layoutManager: {
      type: Object,
    },
    filterConfig: {
      type: Object,
    },
  },
  data() {
    return {
      immediate: true,
      form: {
        atomName: null,
        label: 0,
      },
    };
  },
  computed: {
    pageTitle() {
      return this.$text('Filter');
    },
    userLabels() {
      const labelsAll = this.$store.getters['a/base/userLabels'];
      if (!labelsAll) return null;

      const labels = [{ title: '', value: 0 }];
      for (const key in labelsAll) {
        labels.push({ title: labelsAll[key].text, value: key });
      }
      return labels;
    },
    atomClassTitle() {
      if (!this.atomClass) return '';
      if (this.atomClass.title) return this.atomClass.title;
      const _atomClass = this.getAtomClass(this.atomClass);
      if (!_atomClass) return '';
      return _atomClass.titleLocale;
    },
  },
  watch: {
    atomClass(value) {
      this.atomClassChanged();
    },
  },
  created() {
    // labels
    this.$store.dispatch('a/base/getLabels');
    // init atomClass
    this.atomClassChanged();
  },
  mounted() {
    // immediate
    const $el = this.$$(this.$el);
    const $view = $el.parents('.eb-layout-view');
    this.immediate = $view.is('.eb-layout-panel-view');
  },
  methods: {
    onFormSubmit() {
      this.$refs.buttonSubmit.onClick();
    },
    atomClassChanged() {
      const atomClass = this.atomClass;
      if (!atomClass) {
        this.item = null;
        this.validateParams = null;
      } else {
        // module
        this.$meta.module.use(atomClass.module, () => {
          // validateParams
          this.$api.post('atomClass/validatorSearch', {
            atomClass: {
              module: atomClass.module,
              atomClassName: atomClass.atomClassName,
            },
          }).then(data => {
            this.item = {};
            this.validateParams = {
              module: data.module,
              validator: data.validator,
            };
          });
        });
      }
    },
    onSelectAtomClass() {
      this.$view.navigate('/a/base/atom/selectAtomClass', {
        target: '_self',
        context: {
          params: {
            atomClass: this.atomClass,
            optional: true,
          },
          callback: (code, data) => {
            if (code === 200) {
              this.atomClass = data;
            }
          },
        },
      });
    },
    onPerformSearch() {
      // atomClassExtra
      let atomClassExtra;
      if (this.item) {
        atomClassExtra = {};
        for (const key in this.item) {
          const value = this.item[key];
          // undefined/null/'', except 0/false
          if (value !== undefined && value !== null && value !== '') {
            if (typeof value === 'string') {
              atomClassExtra[`f.${key}`] = { val: value, op: 'like' };
            } else {
              atomClassExtra[`f.${key}`] = value;
            }
          }
        }
      }
      // url
      const queries = {};
      const atomClass = this.atomClass;
      if (atomClass) {
        queries.module = atomClass.module;
        queries.atomClassName = atomClass.atomClassName;
      }
      if (this.where) {
        queries.where = JSON.stringify(this.where);
      }
      queries.mode = this.mode;
      const url = this.$meta.util.combineQueries('/a/base/atom/searchResult', queries);
      this.$view.navigate(url, {
        target: '_self',
        context: {
          params: {
            atomName: this.atomName,
            label: this.label,
            atomClassExtra,
            selectMode: this.selectMode,
          },
          callback: (code, data) => {
            if (code === 200) {
              if (this.mode === 'selectSearch') {
                this.contextCallback(200, data);
              }
            }
          },
        },
      });
    },
    _renderNavbar() {
      return (
        <eb-navbar title={this.pageTitle} eb-back-link="Back">
          <f7-nav-right>
            {!this.immediate && <eb-link ref="buttonSubmit" iconMaterial="search" propsOnPerform={this.onPerformSearch}></eb-link>}
          </f7-nav-right>
        </eb-navbar>
      );
    },
    _renderForm() {
      return (
        <eb-list form inline-labels no-hairlines-md onSubmit={this.onFormSubmit}>
          <eb-list-input v-model={this.form.atomName} label={this.$text('Atom Name')} type="text" clear-button placeholder={this.$text('Atom Name')}></eb-list-input>
          <f7-list-item smartSelect title={this.$text('Label')} smartSelectParams={{ openIn: 'page', closeOnSelect: true }}>
            <eb-select name="label" v-model={this.form.label} options={this.userLabels}></eb-select>
          </f7-list-item>
          <f7-list-item divider></f7-list-item>
          {!this.layoutManager.atomClass && <f7-list-item title={this.$text('Atom Class')} link="#" onClick={this.onSelectAtomClass}>
            <div slot="after">{this.atomClassTitle}</div>
          </f7-list-item>}
        </eb-list>
      );
    },
  },
  render() {
    return (
      <div>
        {this._renderNavbar()}
        {this._renderForm()}
      </div>
    );
  },
};

// src/module-system/a-baselayout/front/src/pages/listLayoutFilter.jsx
import Vue from 'vue';
const ebPageContext = Vue.prototype.$meta.module.get('a-components').options.mixins.ebPageContext;
const ebAtomClasses = Vue.prototype.$meta.module.get('a-base').options.mixins.ebAtomClasses;
export default {
  mixins: [ebPageContext, ebAtomClasses],
  data() {
    return {
      tabId: {
        basic: Vue.prototype.$meta.util.nextId('basic'),
        general: Vue.prototype.$meta.util.nextId('general'),
        category: Vue.prototype.$meta.util.nextId('category'),
        tag: Vue.prototype.$meta.util.nextId('tag'),
      },
      tabName: 'basic',
      //
      form: null,
      formAtomClass: null,
      schemaSearch: null,
      categoriesAll: null,
      tagsAll: null,
      ready: false,
    };
  },
  computed: {
    pageTitle() {
      return this.$text('Filter');
    },
    filterComponentInstance() {
      return this.$refs.filter && this.$refs.filter.getComponentInstance();
    },
    immediate() {
      return this.contextParams.immediate;
    },
    layoutManager() {
      return this.contextParams.layoutManager;
    },
    filterConfig() {
      return this.contextParams.filterConfig;
    },
    //
    userLabels() {
      const labelsAll = this.$store.getters['a/base/userLabels'];
      if (!labelsAll) return null;

      const labels = [{ title: '', value: 0 }];
      for (const key in labelsAll) {
        labels.push({ title: labelsAll[key].text, value: key });
      }
      return labels;
    },
    locales() {
      const locales = this.$store.getState('a/base/locales');
      if (!locales) return [];
      return [{ title: '', value: '' }].concat(locales);
    },
    atomClass() {
      return this.form.atomClass;
    },
    atomClassBase() {
      if (!this.atomClass) return null;
      return this.getAtomClass(this.atomClass);
    },
    atomClassTitle() {
      if (!this.atomClass) return '';
      if (this.atomClass.title) return this.atomClass.title;
      const _atomClass = this.atomClassBase;
      if (!_atomClass) return '';
      return _atomClass.titleLocale;
    },
    stages() {
      const stages = [];
      const atomClassBase = this.atomClassBase;
      for (const key of ['draft', 'formal', 'history']) {
        if (atomClassBase && atomClassBase.simple && key === 'draft') continue;
        stages.push({ title: key.replace(key[0], key[0].toUpperCase()), value: key });
      }
      return stages;
    },
  },
  watch: {
    form: {
      handler() {
        this.onFilterChanged();
      },
      deep: true,
    },
    formAtomClass: {
      handler() {
        this.onFilterChanged();
      },
      deep: true,
    },
  },
  mounted() {
    this.layoutManager.$on('layoutManager:destroy', this.onLayoutManagerDestroy);
  },
  beforeDestroy() {
    this.layoutManager.$off('layoutManager:destroy', this.onLayoutManagerDestroy);
  },
  created() {
    // filter data
    const filterData = this.$meta.util.getProperty(this.layoutManager, 'filter.data');
    this.form = filterData.form;
    this.formAtomClass = filterData.formAtomClass;
    this.schemaSearch = filterData.schemaSearch;
  },
  methods: {
    onAtomClassesReady() {
      this.init();
    },
    async init() {
      // labels
      await this.$store.dispatch('a/base/getLabels');
      // locales
      await this.$store.dispatch('a/base/getLocales');
      // init atomClass
      await this.atomClassChanged(true);
      //
      this.ready = true;
    },
    async loadCategoriesAll(language) {
      const atomClassBase = this.atomClassBase;
      if (!atomClassBase || !atomClassBase.category) return;
      this.categoriesAll = await this.$store.dispatch('a/base/getCategories', {
        atomClass: this.atomClass,
        language,
      });
    },
    async loadTagsAll(language) {
      const atomClassBase = this.atomClassBase;
      if (!atomClassBase || !atomClassBase.tag) return;
      this.tagsAll = await this.$store.dispatch('a/base/getTags', {
        atomClass: this.atomClass,
        language,
      });
    },
    async loadSchemaSearch(atomClass) {
      this.schemaSearch = await this.layoutManager.filter_loadSchemaSearch(atomClass);
    },
    async atomClassChanged(first) {
      const atomClass = this.atomClass;
      if (!atomClass) {
        // reset
        this.categoriesAll = null;
        this.tagsAll = null;
        this.schemaSearch = null;
      } else {
        // switch
        // categories
        await this.loadCategoriesAll(this.form.language);
        // tags
        await this.loadTagsAll(this.form.language);
        // schemaSearch
        if (!first) {
          await this.loadSchemaSearch(atomClass);
        }
      }
    },
    onPerformSearch() {
      this.onFilterChanged(true);
      this.$f7router.back();
    },
    onFilterChanged(force) {
      if (force || this.immediate) {
        this.onFilterDebounce();
      }
    },
    onFilterDebounce: Vue.prototype.$meta.util.debounce(function () {
      this.layoutManager.filter_onChanged({
        form: this.form,
        formAtomClass: this.formAtomClass,
        schemaSearch: this.schemaSearch,
      });
    }, 300),
    onLayoutManagerDestroy() {
      this.$view.close();
    },
    _getFilterComponentOptions() {
      return {
        props: {
          layoutManager: this.layoutManager,
          filterConfig: this.filterConfig,
          filterContainer: this,
        },
      };
    },
    _renderNavbar() {
      const domNavbarRight = this._renderNavbarRight();
      const domNavbarSub = this._renderNavbarSub();
      return (
        <eb-navbar title={this.pageTitle} eb-back-link="Back">
          {domNavbarRight}
          {domNavbarSub}
        </eb-navbar>
      );
    },
    _renderNavbarRight() {
      let domButtonSearch;
      if (!this.immediate) {
        domButtonSearch = <eb-link ref="buttonSubmit" iconMaterial="search" propsOnPerform={this.onPerformSearch}></eb-link>;
      }
      return <f7-nav-right>{domButtonSearch}</f7-nav-right>;
    },
    _renderNavbarSubLink(tabName, tabNameTitle) {
      return (
        <eb-link tabLink={`#${this.tabId[tabName]}`} tabLinkActive={this.tabName === tabName}>
          {this.$text(tabNameTitle)}
        </eb-link>
      );
    },
    _renderNavbarSub() {
      // basic
      const domLinkBasic = this._renderNavbarSubLink('basic', 'Basic');
      // general
      const domLinkGeneral = this._renderNavbarSubLink('general', 'General');
      // category
      let domLinkCategory;
      if (this.atomClassBase && this.atomClassBase.category) {
        domLinkCategory = this._renderNavbarSubLink('category', 'Category');
      }
      // tag
      let domLinkTag;
      if (this.atomClassBase && this.atomClassBase.tag) {
        domLinkTag = this._renderNavbarSubLink('tag', 'Tag');
      }
      return (
        <f7-subnavbar>
          <f7-toolbar top tabbar>
            {domLinkBasic}
            {domLinkGeneral}
            {domLinkCategory}
            {domLinkTag}
          </f7-toolbar>
        </f7-subnavbar>
      );
    },
    _renderTabs() {
      //   <f7-tabs ref="tabs">
      //   <eb-tab-page-content :id="tabId.mine" :tabActive="tabName === 'mine'" data-ref="mine" @tab:show="tabName = 'mine'">
      //     <flowTab ref="mine" slot="list" :container="getContainer('mine')"></flowTab>
      //   </eb-tab-page-content>
      //   <eb-tab-page-content :id="tabId.others" :tabActive="tabName === 'others'" data-ref="others" @tab:show="tabName = 'others'">
      //     <flowTab ref="others" slot="list" :container="getContainer('others')"></flowTab>
      //   </eb-tab-page-content>
      //   <eb-tab-page-content :id="tabId.history" :tabActive="tabName === 'history'" data-ref="history" @tab:show="tabName = 'history'">
      //     <flowTab ref="history" slot="list" :container="getContainer('history')"></flowTab>
      //   </eb-tab-page-content>
      // </f7-tabs>
    },
  },
  render() {
    return (
      <eb-page page-content={false} tabs with-subnavbar>
        {this._renderNavbar()}
        {this._renderTabs()}
      </eb-page>
    );
  },
};
