// src/module-system/a-baselayout/front/src/components/atom/listLayoutList.jsx
import Vue from 'vue';
const ebAtomClasses = Vue.prototype.$meta.module.get('a-base').options.mixins.ebAtomClasses;
export default {
  meta: {
    global: false,
  },
  mixins: [ ebAtomClasses ],
  props: {
    layoutManager: {
      type: Object,
    },
    layoutConfig: {
      type: Object,
    },
  },
  data() {
    return {
    };
  },
  created() {
  },
  methods: {
    getPageTitle() {
      const atomClass = this.getAtomClass(this.layoutManager.atomClass);
      if (!atomClass) return this.$text('Atom');
      return `${this.$text('Atom')}: ${atomClass.titleLocale}`;
    },
    _renderBlockTitle() {
      if (!this.layoutConfig.blocks.title) return null;
      return (
        <eb-navbar title={this.getPageTitle()} eb-back-link="Back">
        </eb-navbar>
      );
    },
  },
  render() {
    return (
      <div>
        {this._renderBlockTitle()}
      </div>
    );
  },
};

// src/module-system/a-detail/front/src/components/detail/listLayoutList/listLayoutList.jsx
export default {
  meta: {
    global: false,
  },
  props: {
    layoutManager: {
      type: Object,
    },
    layoutConfig: {
      type: Object,
    },
  },
  data() {
    return {
      items: [],
    };
  },
  created() {
    this.layoutManager.layout.instance = this;
    this.loadDetails();
  },
  methods: {
    async loadDetails() {
      // params
      const params = this.layoutManager.base_prepareSelectParams();
      // fetch
      const res = await this.$api.post('/a/detail/detail/select', params);
      this.items = res.list;
    },
    getBlockComponentOptions({ blockConfig }) {
      return {
        props: {
          layoutManager: this.layoutManager,
          layout: this,
          blockConfig,
        },
      };
    },
    getItems() {
      return this.items;
    },
    getItemsAll() {
      return this.getItems();
    },
    _renderBlock({ blockName }) {
      const blockConfig = this.layoutConfig.blocks[blockName];
      if (!blockConfig) return null;
      return <eb-component module={blockConfig.component.module} name={blockConfig.component.name} options={this.getBlockComponentOptions({ blockConfig })}></eb-component>;
    },
  },
  render() {
    return (
      <div>
        {this._renderBlock({ blockName: 'title' })}
        {this._renderBlock({ blockName: 'items' })}
      </div>
    );
  },
};
