// src/module-system/a-authsms/front/src/pages/smsProvider/list.jsx
export default {
  data() {
    return {
      items: null,
    };
  },
  computed: {
    ready() {
      return !!this.items;
    },
  },
  created() {
    this.load();
  },
  methods: {
    async load() {
      try {
        // fetch
        this.items = await this.$api.post('scene/list');
      } catch (err) {
        this.$view.toast.show({ text: err.message });
      }
    },
    onPerformItem(event, item, sceneName) {
      this._editSceneConfig(item, sceneName);
    },
    async onPerformItemSceneDelete(event, item, sceneName) {
      await this.$view.dialog.confirm();
      // delete
      await this.$api.post('scene/delete', {
        sceneName,
      });
      // reload
      await this.load();
      // ok
      return true;
    },
    async onPerformItemSceneAdd() {
      // sceneName
      const sceneName = await this.$view.dialog.prompt(this.$text('Please specify the scene name'));
      if (!sceneName || this.items[sceneName]) return;
      // add
      const title = sceneName.replace(sceneName[0], sceneName[0].toUpperCase());
      await this.$api.post('scene/add', {
        sceneName,
        data: {
          title,
        },
      });
      // reload
      await this.load();
    },
    _editSceneConfig(item, sceneName) {
      this.$view.navigate(`/a/mail/scene/config?sceneName=${sceneName}`, {
        context: {
          params: {
            item,
            title: this._editSceneConfig_getTitle(item, sceneName),
            onSaveScene: async data => {
              await this._editSceneConfig_save(item, sceneName, data);
            },
          },
        },
      });
    },
    _editSceneConfig_getTitle(item, sceneName) {
      const title = this.$text('Config');
      return `${title}: ${sceneName}`;
    },
    async _editSceneConfig_save(item, sceneName, data) {
      // save
      const data2 = await this.$api.post('scene/save', {
        sceneName,
        data,
      });
      // change
      this.items[sceneName] = data2;
    },
    _renderItem(item, sceneName) {
      const domActions = [];
      domActions.push(
        <div
          key="actionDelete"
          color="red"
          propsOnPerform={event => this.onPerformItemSceneDelete(event, item, sceneName)}
        >
          <f7-icon slot="media" f7="::delete"></f7-icon>
          <div slot="title">{this.$text('Delete')}</div>
        </div>
      );
      return (
        <eb-list-item
          key={sceneName}
          link="#"
          propsOnPerform={event => this.onPerformItem(event, item, sceneName)}
          swipeout
        >
          <div slot="title">{item.titleLocale}</div>
          <eb-context-menu>
            <div slot="right">{domActions}</div>
          </eb-context-menu>
        </eb-list-item>
      );
    },

    _renderList() {
      if (!this.ready) return;
      const children = [];
      for (const sceneName in this.items) {
        const item = this.items[sceneName];
        children.push(this._renderItem(item, sceneName));
      }
      return <f7-list>{children}</f7-list>;
    },
  },
  render() {
    return (
      <eb-page>
        <eb-navbar large largeTransparent title={this.$text('Mail Management')} eb-back-link="Back">
          <f7-nav-right>
            <eb-link
              ref="buttonAdd"
              iconF7="::add"
              tooltip={this.$text('ActionAddMailScene')}
              propsOnPerform={this.onPerformItemSceneAdd}
            ></eb-link>
          </f7-nav-right>
        </eb-navbar>
        {this._renderList()}
      </eb-page>
    );
  },
};

// src/module-system/a-baseadmin/front/src/pages/tag/list.vue
<template>
  <eb-page ptr @ptr:refresh="onRefresh">
    <eb-navbar large largeTransparent :title="pageTitle" eb-back-link="Back">
      <f7-nav-right>
        <eb-link iconMaterial="add" :onPerform="onPerformAdd"></eb-link>
      </f7-nav-right>
    </eb-navbar>
    <f7-list>
      <eb-list-item class="item" v-for="item of items" :key="item.id" :title="item.tagName" :badge="item.tagAtomCount" link="#" :context="item" :onPerform="onItemClick" swipeout>
        <eb-context-menu>
          <div slot="right">
            <div color="orange" close :context="item" :onPerform="onPerformEdit">{{$text('Edit')}}</div>
            <div color="red" :context="item" :onPerform="onPerformDelete">{{$text('Delete')}}</div>
          </div>
        </eb-context-menu>
      </eb-list-item>
    </f7-list>
    <div v-if="items && items.length===0" class="text-align-center">{{$text('No Data')}}</div>
  </eb-page>
</template>
<script>
export default {
  data() {
    const query = this.$f7route.query;
    const atomClass = {
      module: query.module,
      atomClassName: query.atomClassName,
    };
    const language = query.language;
    const languageTitle = query.languageTitle;
    return {
      atomClass,
      language,
      languageTitle,
      items: null,
    };
  },
  computed: {
    pageTitle() {
      const title = this.$text('Tags');
      if (!this.language) return title;
      return `${title}: ${this.languageTitle}`;
    },
  },
  created() {
    this.reload();
  },
  methods: {
    onRefresh(done) {
      done();
      this.reload();
    },
    reload() {
      // all tags
      const options = {
        where: { language: this.language },
        orders: [
          [ 'tagName', 'asc' ],
        ],
      };
      this.$api.post('/a/base/tag/list', {
        atomClass: this.atomClass,
        options,
      }).then(res => {
        this.items = res.list;
      });
    },
    async onPerformAdd() {
      const tagName = await this.$view.dialog.prompt(this.$text('Please specify the tag name'));
      if (!tagName) return;
      await this.$api.post('/a/base/tag/add', {
        atomClass: this.atomClass,
        data: {
          tagName,
          language: this.language,
        },
      });
      this.reload();
    },
    async onItemClick(event, item) {
      await this.onPerformEdit(event, item);
    },
    async onPerformEdit(event, item) {
      const tagName = await this.$view.dialog.prompt(this.$text('Please specify the new tag name'));
      if (!tagName) return;
      await this.$api.post('/a/base/tag/save', {
        tagId: item.id,
        data: {
          tagName,
        },
      });
      const index = this.items.findIndex(_item => _item.id === item.id);
      if (index !== -1) {
        this.items.splice(index, 1, { ...item, tagName });
      }
    },
    async onPerformDelete(event, item) {
      await this.$view.dialog.confirm();
      await this.$api.post('/a/base/tag/delete', { tagId: item.id });
      this.$meta.util.swipeoutClose(event.target);
      const index = this.items.findIndex(_item => _item.id === item.id);
      if (index !== -1) {
        this.items.splice(index, 1);
      }
    },
  },
};

</script>
<style lang="less" scoped>
</style>
