// src/module-system/a-components-sync/front/src/common/validate/validateItem.jsx
import validateActionModule from './validateActionModule.js';
import validateComputedValue from './validateComputedValue.js';
import validateComputedDisplay from './validateComputedDisplay.js';
import renderSearchStates from './render/renderSearchStates.jsx';
import renderProperties from './render/renderProperties.jsx';
import renderComponent from './render/renderComponent.jsx';
import renderComponentAction from './render/renderComponentAction.jsx';
import renderGroup from './render/renderGroup.jsx';
import renderPanel from './render/renderPanel.jsx';
import renderText from './render/renderText.jsx';
import renderDatepicker from './render/renderDatepicker.jsx';
import renderDateRange from './render/renderDateRange.jsx';
import renderFile from './render/renderFile.jsx';
import renderToggle from './render/renderToggle.jsx';
import renderSelect from './render/renderSelect.jsx';
import renderLink from './render/renderLink.jsx';
import renderLanguage from './render/renderLanguage.jsx';
import renderCategory from './render/renderCategory.jsx';
import renderTags from './render/renderTags.jsx';
import renderResourceType from './render/renderResourceType.jsx';
import renderJson from './render/renderJson.jsx';
import renderMarkdown from './render/renderMarkdown.jsx';
import renderDetails from './render/renderDetails.jsx';
import renderDetailsStat from './render/renderDetailsStat.jsx';
import renderAtom from './render/renderAtom.jsx';
import renderAtomClass from './render/renderAtomClass.jsx';
import renderDivider from './render/renderDivider.jsx';
import renderUserLabel from './render/renderUserLabel.jsx';

export default {
  mixins: [
    renderSearchStates,
    validateActionModule,
    validateComputedValue,
    validateComputedDisplay,
    renderProperties,
    renderComponent,
    renderComponentAction,
    renderGroup,
    renderPanel,
    renderText,
    renderDatepicker,
    renderDateRange,
    renderFile,
    renderToggle,
    renderSelect,
    renderLink,
    renderLanguage,
    renderCategory,
    renderTags,
    renderResourceType,
    renderJson,
    renderMarkdown,
    renderDetails,
    renderDetailsStat,
    renderAtom,
    renderAtomClass,
    renderDivider,
    renderUserLabel,
  ],
  props: {
    parcel: {
      type: Object,
    },
    dataKey: {
      type: String,
    },
    property: {
      type: Object,
    },
    meta: {
      type: Object,
    },
    root: {
      type: Boolean,
      default: false,
    },
  },
  data() {
    return {
      validate: null,
    };
  },
  watch: {
    parcel() {
      this.parcelChanged();
    },
  },
  created() {
    this.validate = this.getValidate();
  },
  beforeDestroy() {
    this.validate = null;
  },
  methods: {
    parcelChanged() {
      this.__computed_value_init();
      this.__computed_display_init();
    },
    getValidate() {
      let parent = this.$parent;
      while (parent) {
        if (parent.$options._componentTag === 'eb-validate') break;
        parent = parent.$parent;
      }
      return parent;
    },
    _handleComputedValue(parcel, key, property) {
      const ebComputed = property.ebComputed;
      if (!ebComputed) return;
      this.__computed_value.register({
        parcel,
        name: key,
        expression: ebComputed.expression,
        dependencies: ebComputed.dependencies,
        immediate: ebComputed.immediate,
      });
    },
    getValue(parcel, key) {
      const property = parcel.properties[key];
      const _value = parcel.data[key];
      if (!property) {
        return _value;
      }
      this._handleComputedValue(parcel, key, property);
      if (!this.checkIfEmptyForSelect(_value)) return _value;
      if (this.checkIfEmptyForSelect(property.default)) return _value;
      return property.default;
    },
    setValue(parcel, key, value) {
      let property;
      if (parcel === this.parcel && key === this.dataKey && this.property) {
        property = this.property;
      } else {
        property = parcel.properties[key];
      }
      // typed value
      const _value = this._convertValueType(property, value);

      const _valueOld = parcel.data[key];

      this.$set(parcel.data, key, _value); // always set as maybe Object

      // dataSrc
      //   always set value for !property
      if (!property || property.type) {
        // change src
        this.$set(parcel.dataSrc, key, _value);
        // emit changed
        if (!this._checkIfEqual(_valueOld, _value)) {
          this.$emit('change', _value);
          this.validate.$emit('validateItem:change', key, _value);
          this.validate.$emit('validateItemChange', key, _value);
        }
      }
    },
    _checkIfEqual(value1, value2) {
      if (value1 === value2) return true;
      if (!value1 || !value2) return false;
      // special for date
      if (value1 instanceof Date && value2 instanceof Date && value1.getTime() === value2.getTime()) return true;
      // others
      return false;
    },
    _convertValueType(property, value) {
      if (!property) return value;
      // special for select empty
      if (property.ebType === 'select' && this.checkIfEmptyForSelect(value)) {
        return null; // for distinguish from 0
      }
      // others
      let _value;
      if (property.type === 'number') {
        if (isNaN(value)) {
          _value = value;
        } else {
          _value = Number(value);
        }
      } else if (property.type === 'integer') {
        if (isNaN(value)) {
          _value = value;
        } else {
          _value = parseInt(Number(value));
        }
      } else if (property.type === 'boolean') {
        _value = Boolean(value);
      } else if (property.type === 'string') {
        _value = String(value);
      } else {
        _value = value;
      }
      // ok
      return _value;
    },
    checkIfEmptyForSelect(value) {
      return value === '' || value === undefined || value === null;
    },
    adjustDataPath(dataPath) {
      if (!dataPath) return dataPath;
      if (dataPath[0] !== '/') return this.validate.dataPathRoot + dataPath;
      return dataPath;
    },
    getTitle(context, notHint) {
      const { property } = context;
      // not use 'key' as default title
      let title = property.ebTitle || '';
      if (title) {
        title = this.$text(title);
      }
      // ignore panel/group/toggle
      const ebType = property.ebType;
      if (ebType === 'panel' || ebType === 'group' || ebType === 'group-flatten' || ebType === 'toggle') return title;
      // only edit
      if (this.validate.readOnly || property.ebReadOnly) return title;
      // hint
      if (!notHint) {
        // config
        let hint = this.validate.host && this.validate.host.hint;
        if (!hint && hint !== false) {
          hint = this.$config.validate.hint;
        }
        if (hint === false) {
          return title;
        }
        const hintOptional = hint.optional;
        const hintMust = hint.must;
        // check optional
        if (hintOptional && !property.notEmpty) {
          return `${title}${this.$text(hintOptional)}`;
        }
        // check must
        if (hintMust && property.notEmpty) {
          return `${title}${this.$text(hintMust)}`;
        }
      }
      // default
      return title;
    },
    getPlaceholder(context) {
      const { property } = context;
      if (this.validate.readOnly || property.ebReadOnly) return undefined;
      return property.ebDescription ? this.$text(property.ebDescription) : this.getTitle(context, true);
    },
    onSubmit(event) {
      this.validate.onSubmit(event);
    },
    getParcel() {
      return this.parcel || this.validate.parcel;
    },
    _combinePropertyMeta({ property, meta, dataPath }) {
      const metaValidateProperty = this.$meta.util.getProperty(this.validate, `meta.properties.${dataPath}`);
      if (!metaValidateProperty && !meta) return property;
      return this.$meta.util.extend({}, property, metaValidateProperty, meta);
    },
    getContext({ parcel, key, property, meta }) {
      // dataPath
      const dataPath = parcel.pathParent + key;
      // property
      property = this._combinePropertyMeta({ property, meta, dataPath });
      // patch getValue/setValue
      const patchGetValue = this.$meta.util.getProperty(property, 'ebPatch.getValue');
      const patchSetValue = this.$meta.util.getProperty(property, 'ebPatch.setValue');
      const patchGetValueGlobal = this.$meta.util.getProperty(this.validate, 'meta.ebPatch.getValue');
      const patchSetValueGlobal = this.$meta.util.getProperty(this.validate, 'meta.ebPatch.setValue');
      // context
      const context = {
        validate: this.validate,
        validateItem: this,
        parcel,
        key,
        property,
        dataPath,
        meta,
        getTitle: notHint => {
          return this.getTitle(context, notHint);
        },
        getValue: name => {
          const propertyName = name || key;
          let value = this.getValue(parcel, propertyName);
          if (patchGetValue && (!name || name === key)) {
            // only patch this
            value = patchGetValue(value);
          }
          if (patchGetValueGlobal) {
            value = patchGetValueGlobal(value, propertyName);
          }
          return value;
        },
        setValue: (value, name) => {
          const propertyName = name || key;
          if (patchSetValueGlobal) {
            value = patchSetValueGlobal(value, propertyName);
          }
          if (patchSetValue && (!name || name === key)) {
            // only patch this
            value = patchSetValue(value);
          }
          this.setValue(parcel, propertyName, value);
        },
      };
      return context;
    },
    renderRoot() {
      if (!this.validate.ready) return <div></div>;
      // context
      const context = {
        parcel: this.getParcel(),
      };
      // renderProperties
      const children = this.renderProperties(context);
      const props = {
        form: true,
        noHairlinesMd: true,
        inlineLabels: !this.$config.form.floatingLabel,
      };
      return (
        <eb-list staticClass="eb-list-row" {...{ props }} onSubmit={this.onSubmit}>
          {children}
        </eb-list>
      );
    },
    renderItem() {
      if (!this.validate.ready) return <div></div>;
      // context
      const parcel = this.getParcel();
      const key = this.dataKey;
      const context = this.getContext({
        parcel,
        key,
        property: this.property || parcel.properties[key],
        meta: this.meta,
      });
      // renderItem
      return this._renderItem(context);
    },
    _renderItem(context) {
      const { parcel, key, property } = context;
      // ebType
      const ebType = property.ebType;
      // ignore if not specified
      if (!ebType) return null;
      // ebDisplay
      if (!this._handleComputedDisplay(parcel, key, property)) {
        return null;
      }
      // render
      if (ebType === 'group') {
        // group
        return this.renderGroup(context);
      } else if (ebType === 'panel') {
        // panel
        return this.renderPanel(context);
      } else if (ebType === 'text') {
        // text
        return this.renderText(context);
      } else if (ebType === 'toggle') {
        // toggle
        return this.renderToggle(context);
      } else if (ebType === 'select') {
        // select
        return this.renderSelect(context);
      } else if (ebType === 'file') {
        // file
        return this.renderFile(context);
      } else if (ebType === 'datepicker') {
        // datepicker
        return this.renderDatepicker(context);
      } else if (ebType === 'dateRange') {
        // datepicker
        return this.renderDateRange(context);
      } else if (ebType === 'link') {
        // link
        return this.renderLink(context);
      } else if (ebType === 'component') {
        // component
        return this.renderComponent(context);
      } else if (ebType === 'component-action') {
        // component-action
        return this.renderComponentAction(context);
      } else if (ebType === 'language') {
        // language
        return this.renderLanguage(context);
      } else if (ebType === 'category') {
        // category
        return this.renderCategory(context);
      } else if (ebType === 'tags') {
        // tags
        return this.renderTags(context);
      } else if (ebType === 'resourceType') {
        // resourceType
        return this.renderResourceType(context);
      } else if (ebType === 'json') {
        // json
        return this.renderJson(context);
      } else if (ebType === 'markdown') {
        // json
        return this.renderMarkdown(context);
      } else if (ebType === 'markdown-content') {
        // json
        return this.renderMarkdownContent(context);
      } else if (ebType === 'markdown-content-cms') {
        // json
        return this.renderMarkdownContentCms(context);
      } else if (ebType === 'details') {
        // details
        return this.renderDetails(context);
      } else if (ebType === 'detailsStat') {
        // details
        return this.renderDetailsStat(context);
      } else if (ebType === 'atom') {
        // atom
        return this.renderAtom(context);
      } else if (ebType === 'atomClass') {
        // atomClass
        return this.renderAtomClass(context);
      } else if (ebType === 'divider') {
        // divider
        return this.renderDivider(context);
      } else if (ebType === 'userLabel') {
        // userLabel
        return this.renderUserLabel(context);
      }
      // not support
      return <div>{`not support: ${ebType}`}</div>;
    },
    _handleComputedDisplay(parcel, key, property) {
      // check if specify ebDisplay
      const ebDisplay = property.ebDisplay;
      if (!ebDisplay) return true;
      // check host.stage
      if (!this._handleComputedDisplay_checkHost(ebDisplay, 'stage')) {
        return false;
      }
      // check host.mode
      if (!this._handleComputedDisplay_checkHost(ebDisplay, 'mode')) {
        return false;
      }
      // check if specify expression
      if (!ebDisplay.expression) {
        return true;
      }
      // try to register always, for maybe disposed when parcel changed
      this.__computed_display.register({
        parcel,
        name: key,
        expression: ebDisplay.expression,
        dependencies: ebDisplay.dependencies,
        immediate: true, // always
      });
      // check current value
      return !!this.__computed_display_getValue(parcel, key);
    },
    _handleComputedDisplay_checkHost(ebDisplay, attr) {
      const hostAttr = ebDisplay.host && ebDisplay.host[attr];
      if (!hostAttr) return true;
      const current = this.validate.host && this.validate.host[attr];
      return current === hostAttr;
    },
  },
};

// src/module-system/a-components-sync/front/src/components/validateItem.vue
<script>
export default {
  meta: {
    global: true,
  },
  name: 'eb-list-item-validate',
  render(c) {
    return this.renderItem(c);
  },
  props: {
    dataKey: {
      type: String,
    },
    pathParent: {
      type: String,
      default: '',
    },
    meta: {
      type: Object,
    },
  },
  data() {
    return {
      validate: null,
    };
  },
  created() {
    this.validate = this.getValidate();
  },
  beforeDestroy() {
    this.validate = null;
  },
  methods: {
    getValidate() {
      let parent = this.$parent;
      while (parent) {
        if (parent.$options._componentTag === 'eb-validate') break;
        parent = parent.$parent;
      }
      return parent;
    },
    getMetaValue(key) {
      // 1. item
      const value = this.meta ? this.meta[key] : undefined;
      if (value !== undefined) return value;
      // 2. validate
      const validateMeta = this.validate.meta;
      return validateMeta ? validateMeta[key] : undefined;
    },
    getValue(data, key, property) {
      const _value = data[key];
      if (!this.checkIfEmptyForSelect(_value)) return _value;
      if (this.checkIfEmptyForSelect(property.default)) return _value;
      return property.default;
    },
    setValue(data, key, value, property) {
      let _value;

      if (property.ebType === 'select' && this.checkIfEmptyForSelect(value)) {
        _value = null; // for distinguish from 0
      } else {
        if (property.type === 'number') {
          _value = Number(value);
        } else if (property.type === 'boolean') {
          _value = Boolean(value);
        } else {
          _value = value;
        }
      }

      const _valueOld = data[key];

      this.$set(data, key, _value); // always set as maybe Object

      if (_valueOld !== _value) {
        this.$emit('change', _value);
        this.validate.$emit('validateItem:change', key, _value);
      }
    },
    checkIfEmptyForSelect(value) {
      return value === '' || value === undefined || value === null;
    },
    adjustDataPath(dataPath) {
      if (!dataPath) return dataPath;
      if (dataPath[0] !== '/') return this.validate.dataPathRoot + dataPath;
      return dataPath;
    },
    getTitle(key, property) {
      const title = this.$text(property.ebTitle || key);
      // ignore panel/group/toggle
      const ebType = property.ebType;
      if (ebType === 'panel' || ebType === 'group' || ebType === 'toggle') return title;
      // only edit
      if (this.validate.readOnly || property.ebReadOnly) return title;
      // config
      const hint = this.getMetaValue('hint') || this.$config.validate.hint;
      const hintOptional = hint.optional;
      const hintMust = hint.must;
      // check optional
      if (hintOptional && !property.notEmpty) {
        return `${title}(${this.$text(hintOptional)})`;
      }
      // check must
      if (hintMust && property.notEmpty) {
        return `${title}(${this.$text(hintMust)})`;
      }
      // default
      return title;
    },
    renderItem(c) {
      if (!this.validate.data || !this.validate.schema) return c('div');
      return this._renderItem(c, this.validate.data, this.validate.schema.properties, this.dataKey, this.pathParent);
    },
    _renderItem(c, data, properties, key, pathParent) {
      const property = properties[key];
      // ignore if not specified
      if (!property.ebType) return null;
      // panel
      if (property.ebType === 'panel') {
        return this.renderPanel(c, data, pathParent, key, property);
      }
      // group
      else if (property.ebType === 'group') {
        return this.renderGroup(c, data, pathParent, key, property);
      }
      // text
      else if (property.ebType === 'text') {
        return this.renderText(c, data, pathParent, key, property);
      }
      // toggle
      else if (property.ebType === 'toggle') {
        return this.renderToggle(c, data, pathParent, key, property);
      }
      // select
      else if (property.ebType === 'select') {
        return this.renderSelect(c, data, pathParent, key, property);
      }
      // file
      else if (property.ebType === 'file') {
        return this.renderFile(c, data, pathParent, key, property);
      }
      // file
      else if (property.ebType === 'datepicker') {
        return this.renderDatepicker(c, data, pathParent, key, property);
      }
      // not support
      return c('div', {
        domProps: {
          innerText: `not support: ${property.ebType}`,
        },
      });
    },
    renderProperties(c, data, properties, pathParent) {
      let children = [];
      for (const key in properties) {
        const item = this._renderItem(c, data, properties, key, pathParent);
        if (item) {
          if (Array.isArray(item)) {
            children = children.concat(item);
          } else {
            children.push(item);
          }
        }
      }
      return children;
    },
    renderPanel(c, data, pathParent, key, property) {
      const dataPath = pathParent + key + '/';
      return c('eb-list-item-panel', {
        key,
        attrs: {
          link: '#',
          title: this.getTitle(key, property),
          dataPath,
        },
        on: {
          click: () => {
            const params = this.validate.params;
            const verrors = this.validate.verrors;
            this.$view.navigate('/a/validation/validate', {
              target: '_self',
              context: {
                params: {
                  params: {
                    module: params.module,
                    validator: params.validator,
                    schema: property.$ref,
                  },
                  data: data[key],
                  dataPathRoot: this.adjustDataPath(dataPath),
                  errors: verrors ? verrors.slice(0) : null,
                  readOnly: this.validate.readOnly || property.ebReadOnly,
                },
                callback: (code, res) => {
                  if (code) {
                    this.setValue(data, key, res.data, property);
                    this.validate.verrors = res.errors;
                  }
                },
              },
            });
          },
        },
      });
    },
    renderGroup(c, data, pathParent, key, property) {
      // children
      const children = this.renderProperties(c, data[key], property.properties, `${pathParent}${key}/`);
      // group
      const group = c('f7-list-item', {
        key,
        attrs: {
          groupTitle: true,
          title: this.getTitle(key, property),
        },
      });
      // combine
      children.unshift(group);
      return c('div', children);
    },
    renderText(c, data, pathParent, key, property) {
      const title = this.getTitle(key, property);
      if ((this.validate.readOnly || property.ebReadOnly) && !property.ebTextarea) {
        return c('f7-list-item', {
          key,
          staticClass: '',
          attrs: {
            after: data[key] ? data[key].toString() : null,
          },
        }, [
          c('div', {
            slot: 'title',
            staticClass: property.ebReadOnly ? 'text-color-gray' : '',
            domProps: { innerText: title },
          }),
        ]);
      }
      const placeholder = property.ebDescription ? this.$text(property.ebDescription) : title;
      const info = property.ebHelp ? this.$text(property.ebHelp) : undefined;
      let type;
      if (property.ebSecure) {
        type = 'password';
      } else if (property.ebTextarea) {
        type = 'textarea';
      } else if (property.ebInputType) {
        type = property.ebInputType;
      } else {
        type = 'text';
      }
      return c('eb-list-input', {
        key,
        attrs: {
          floatingLabel: this.$config.form.floatingLabel,
          type,
          placeholder,
          info,
          resizable: property.ebTextarea,
          clearButton: !this.validate.readOnly && !property.ebReadOnly,
          dataPath: pathParent + key,
          value: this.getValue(data, key, property),
          disabled: this.validate.readOnly || property.ebReadOnly,
        },
        on: {
          input: value => {
            this.setValue(data, key, value, property);
          },
        },
      }, [
        c('div', {
          slot: 'label',
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          domProps: { innerText: title },
        }),
      ]);
    },
    renderDatepicker(c, data, pathParent, key, property) {
      const title = this.getTitle(key, property);
      // should format date
      // // the form is readOnly
      // if (this.validate.readOnly || property.ebDisabled) {
      //   return c('f7-list-item', {
      //     key,
      //     staticClass: '',
      //     attrs: {
      //       title,
      //       after: data[key] ? data[key].toString() : null,
      //     },
      //   });
      // }
      const placeholder = property.ebDescription ? this.$text(property.ebDescription) : title;
      const info = property.ebHelp ? this.$text(property.ebHelp) : undefined;
      // value
      let value = this.getValue(data, key, property);
      if (!value) {
        value = [];
      } else if (!Array.isArray(value)) {
        value = [value];
      }
      // input
      return c('eb-list-input', {
        key,
        attrs: {
          floatingLabel: this.$config.form.floatingLabel,
          type: 'datepicker',
          placeholder,
          info,
          resizable: false,
          clearButton: !this.validate.readOnly && !property.ebDisabled,
          dataPath: pathParent + key,
          value,
          readonly: true, // always
          disabled: this.validate.readOnly || property.ebDisabled,
        },
        props: {
          calendarParams: property.ebParams,
        },
        on: {
          'calendar:change': values => {
            // date or array of date
            if (property.type === 'array') {
              this.setValue(data, key, values, property);
            } else {
              this.setValue(data, key, values[0] || null, property);
            }
          }
        },
      }, [
        c('div', {
          slot: 'label',
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          domProps: { innerText: title },
        }),
      ]);
    },
    renderFile(c, data, pathParent, key, property) {
      const title = this.getTitle(key, property);
      if ((this.validate.readOnly || property.ebReadOnly) && !property.ebTextarea) {
        return c('f7-list-item', {
          key,
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          attrs: {
            after: data[key] ? data[key].toString() : null,
          },
        }, [
          c('div', {
            slot: 'title',
            staticClass: property.ebReadOnly ? 'text-color-gray' : '',
            domProps: { innerText: title },
          }),
        ]);
      }
      const placeholder = property.ebDescription ? this.$text(property.ebDescription) : title;
      const info = property.ebHelp ? this.$text(property.ebHelp) : undefined;
      let type;
      if (property.ebSecure) {
        type = 'password';
      } else if (property.ebTextarea) {
        type = 'textarea';
      } else {
        type = 'text';
      }
      // mode
      const mode = this.getMetaValue('mode') || property.ebParams.mode;
      // atomId
      const atomId = this.getMetaValue('atomId') || property.ebParams.atomId || 0;
      // attachment
      const attachment = this.getMetaValue('attachment') || property.ebParams.attachment;
      // flag
      const flag = this.getMetaValue('flag') || property.ebParams.flag;
      // accept
      const accept = this.getMetaValue('accept') || property.ebParams.accept;
      // render
      return c('eb-list-input', {
        key,
        attrs: {
          floatingLabel: this.$config.form.floatingLabel,
          type,
          placeholder,
          info,
          resizable: property.ebTextarea,
          clearButton: !this.validate.readOnly && !property.ebReadOnly,
          dataPath: pathParent + key,
          value: this.getValue(data, key, property),
          disabled: this.validate.readOnly || property.ebReadOnly,
        },
        on: {
          input: value => {
            this.setValue(data, key, value, property);
          },
          focus: event => {
            const upload = this.$$(event.target).closest('li').find('.eb-input-file-upload');
            const timeoutId = upload.data('timeoutId');
            if (timeoutId) {
              window.clearTimeout(timeoutId);
              upload.data('timeoutId', 0);
            }
            upload.show();
          },
          blur: () => {
            const upload = this.$$(event.target).closest('li').find('.eb-input-file-upload');
            const timeoutId = window.setTimeout(() => {
              upload.data('timeoutId', 0);
              upload.hide();
            }, 300);
            upload.data('timeoutId', timeoutId);
          },
        },
      }, [
        c('div', {
          slot: 'label',
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          domProps: { innerText: title },
        }),
        c('eb-button', {
          slot: 'root-end',
          staticClass: 'eb-input-file-upload',
          domProps: { innerText: this.$text('Upload') },
          props: {
            onPerform: () => {
              this.$view.navigate('/a/file/file/upload', {
                target: '_self',
                context: {
                  params: {
                    mode,
                    atomId,
                    attachment,
                    flag,
                    accept,
                  },
                  callback: (code, value) => {
                    if (code === 200) {
                      this.setValue(data, key, value.downloadUrl, property);
                    }
                  },
                },
              });
            },
          },
        }),
      ]);
    },
    renderToggle(c, data, pathParent, key, property) {
      const title = this.getTitle(key, property);
      return c('f7-list-item', {
        key,
      }, [
        c('div', {
          slot: 'title',
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          domProps: { innerText: title },
        }),
        c('eb-toggle', {
          slot: 'after',
          attrs: {
            dataPath: pathParent + key,
            value: this.getValue(data, key, property),
            disabled: this.validate.readOnly || property.ebReadOnly,
          },
          on: {
            input: value => {
              this.setValue(data, key, value, property);
            },
          },
        }),
      ]);
    },
    renderSelect(c, data, pathParent, key, property) {
      const title = this.getTitle(key, property);
      const valueCurrent = this.getValue(data, key, property);
      const attrs = {
        name: key,
        dataPath: pathParent + key,
        value: valueCurrent,
        readOnly: this.validate.readOnly || property.ebReadOnly,
      };
      const metaOptions = this.getMetaValue('options');
      if (metaOptions) attrs.options = metaOptions;
      if (!metaOptions && property.ebOptions) attrs.options = property.ebOptions;
      if (property.ebOptionsUrl) {
        attrs.optionsUrl = property.ebOptionsUrl;
        attrs.optionsUrlParams = property.ebOptionsUrlParams;
      }
      attrs.optionsBlankAuto = property.ebOptionsBlankAuto;
      if (property.ebOptionTitleKey) attrs.optionTitleKey = property.ebOptionTitleKey;
      if (property.ebOptionValueKey) attrs.optionValueKey = property.ebOptionValueKey;
      if (property.ebMultiple) attrs.multiple = property.ebMultiple;
      // specially, not showing blank option when notEmpty and has value
      if (property.notEmpty && !this.checkIfEmptyForSelect(valueCurrent)) {
        attrs.optionsBlankAuto = false;
        if (attrs.options && attrs.options.length > 0) {
          const opt = attrs.options[0];
          if (!opt || this.checkIfEmptyForSelect(opt.value)) {
            attrs.options.shift();
          }
        }
      }
      // render
      return c('eb-list-item', {
        key,
        attrs: {
          smartSelect: !this.validate.readOnly && !property.ebReadOnly,
          //title,
          smartSelectParams: property.ebParams || { openIn: 'page', closeOnSelect: true },
        },
      }, [
        c('div', {
          slot: 'title',
          staticClass: property.ebReadOnly ? 'text-color-gray' : '',
          domProps: { innerText: title },
        }),
        c('eb-select', {
          attrs,
          on: {
            input: value => {
              this.setValue(data, key, value, property);
            },
          },
        }),
      ]);
    },
  },
};

</script>
<style scoped>
</style>
